# Generated by Django 5.2 on 2025-04-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('downloads', models.FloatField(default=0.0)),
                ('storage', models.IntegerField(default=0)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('Sh', 'Shooter'), ('AR', 'Arcade'), ('RA', 'Racing')], default='AC', max_length=2)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
