# Generated by Django 5.2 on 2025-04-11 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='added_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='game',
            name='played_hours',
            field=models.IntegerField(default=40),
        ),
    ]
